"""add max_active_orders to canteens

Revision ID: 0002
Revises: 0001_initial
Create Date: 2026-02-05 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002'
down_revision = '0001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('canteens', sa.Column('max_active_orders', sa.Integer(), nullable=False, server_default='20'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('canteens', 'max_active_orders')
    # ### end Alembic commands ###